import pyautogui
import pyperclip
import time

time.sleep(5)
def countdown():
    pyautogui.write("10...")
    pyautogui.write(['enter'])
    time.sleep(1)
    pyautogui.write("9...")
    pyautogui.write(['enter'])
    time.sleep(1)
    pyautogui.write("8...")
    pyautogui.write(['enter'])
    time.sleep(1)
    pyautogui.write("7...")
    pyautogui.write(['enter'])
    time.sleep(1)
    pyautogui.write("6...")
    pyautogui.write(['enter'])
    time.sleep(1)
    pyautogui.write("5...")
    pyautogui.write(['enter'])
    time.sleep(1)
    pyautogui.write("4...")
    pyautogui.write(['enter'])
    time.sleep(1)
    pyautogui.write("3...")
    pyautogui.write(['enter'])
    time.sleep(1)
    pyautogui.write("2...")
    pyautogui.write(['enter'])
    time.sleep(1)
    pyautogui.write("1...")
    pyautogui.write(['enter'])
    time.sleep(1)
    pyautogui.write("Let's Go!")
    pyautogui.write(['enter'])
    time.sleep(1)
    time.sleep(1)
def spam(msg, emoji):
    pyperclip.copy(emoji)
    i = 0
    while i < 100:
        pyautogui.write(msg)
        pyautogui.hotkey('ctrl', 'v')
        time.sleep(0.5)
        pyautogui.write(['enter'])
        i += 1
def spam_loop(x, msg_loop, emoji_loop):
    p = 0
    while p < x:
        spam(msg_loop, emoji_loop)
        p += 1

spam_loop(6, "Anime SUCKS!! ", "\U0001F922 \U0001F92E")
spam_loop(3, "Flood alert! ", "\U000026a0")
spam_loop(46, "", "\N{egg}\N{penguin}")
spam_loop(46, "Happy Sufferin' 2020! ", "\U0001F608 \U00002620")
spam_loop(46, "It's 20k for the fam! ", "\U0001F64C")
spam_loop(46, "_Sweet Dreams_ ", "\U0001F634")
spam_loop(46, "We're almost done! Let's Go!! ", "\U0001F525 \U0001F525")
spam_loop(20, "Approaching the finish line... ", "\U0001F3CE \U0001F3C1")

pyautogui.write("Woo hoo! Target accomplished!!")
time.sleep(1)
pyautogui.write(['enter'])
pyperclip.copy("\U0001F3AF\U0001F4AF")
pyautogui.hotkey('ctrl', 'v')
time.sleep(1)
pyautogui.write(['enter'])
pyperclip.copy("\U0001F389\U0001F38A")
pyautogui.hotkey('ctrl', 'v')
time.sleep(1)
pyautogui.write(['enter'])
pyautogui.write("My fingers are in flames due to the friction caused by the keys! ")
pyperclip.copy("\U0001F525 \U0001F62B")
pyautogui.hotkey('ctrl', 'v')
time.sleep(1)
pyautogui.write(['enter'])
pyautogui.write("That was so fun! The night shift was worth it. Now I'm going to sleep. Gn people! ")
pyperclip.copy("\U0001F62A \U0001F4A4")
pyautogui.hotkey('ctrl', 'v')
time.sleep(1)
pyautogui.write(['enter'])
pyautogui.write("SpammersUnite")
pyperclip.copy("\U00002122")
pyautogui.hotkey('ctrl', 'v')
pyautogui.write("!!")
time.sleep(1)
pyautogui.write(['enter'])
pyperclip.copy("\U0000270C")
pyautogui.hotkey('ctrl', 'v')
time.sleep(1)
pyautogui.write(['enter'])
pyautogui.write("I'll do this during exams as well. I'm gonna have a blast!! ")
pyperclip.copy("\U0001F929 \U0001F525")
pyautogui.hotkey('ctrl', 'v')
time.sleep(1)
pyautogui.write(['enter'])
time.sleep(600)
pyautogui.hotkey('alt', 'space')
time.sleep(15)
pyautogui.write("Shut")
time.sleep(10)
pyautogui.write(['enter'])
time.sleep(2)
pyautogui.write(['enter'])